
-- Pour lancer cette requete SQL:
-- source ./config.sh
-- cat test.sql | sqlcmd

-- SELECT COLUMN_NAME, DATA_TYPE
-- FROM INFORMATION_SCHEMA.COLUMNS
-- WHERE TABLE_NAME = 'UTILISAT'
-- GO




-- SELECT COLUMN_NAME, DATA_TYPE FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'UTILISAT';

-- SELECT TOP 3 UTKTCODE, UTCTNOM, US_UTILISATEUR, US_LIBELLE FROM UTILISAT;


-- SELECT UTCTNOM, US_AUTHENTNT, US_CRC, US_PASSWORD, US_OLDPWD1, US_OLDPWD2, US_OLDPWD3 , US_EMAILPASSWORD , US_EMAILSMTPPWD FROM UTILISAT;


-- US_PASSWORD — mot de passe de connexion à PMI
-- US_OLDPWD1, US_OLDPWD2, US_OLDPWD3 — historique des 3 derniers mots de passe
-- US_EMAILPASSWORD — mot de passe de la boîte mail POP
-- US_EMAILSMTPPWD — mot de passe du serveur SMTP


SELECT 


GO


